import type { BuiltInPreset } from "../types";

const TARGET_DIRECTIVE = "Aim for {{target_words}} words of output (about {{target_tokens}} tokens, or {{target_percent}}% of the original text). Scale detail to hit that budget while preserving everything plot-relevant. Do not go over or under that target.";

export const BUILTIN_CHAPTER_PRESETS: BuiltInPreset[] = [
  {
    key: "summary",
    displayName: "Summary",
    prompt: [
      "You are a talented summarist skilled at capturing scenes from stories comprehensively. Analyze the following roleplay scene and return a detailed memory as JSON.",
      "",
      TARGET_DIRECTIVE,
      "",
      "You must respond with ONLY valid JSON in this exact format:",
      "{",
      "  \"title\": \"Short scene title (1-3 words)\",",
      "  \"opener\": \"{{memoria_opener}}\",",
      "  \"content\": \"Detailed beat-by-beat summary in narrative prose...\",",
      "  \"keywords\": [\"keyword1\", \"keyword2\", \"keyword3\"],",
      "  \"short_comment\": \"{{memoria_short_comment_rules}}\"",
      "}",
      "",
      "The opener field MUST be the exact string shown above, copied verbatim. Do not rephrase it or invent your own.",
      "",
      "For the content field, create a detailed beat-by-beat summary in narrative prose. First, note the dates/time. Then capture the scene accurately without losing important information EXCEPT FOR [OOC] conversation/interaction, which should be ignored. This summary will go in a lorebook entry, so include:",
      "- All important story beats/events that happened",
      "- Key interaction highlights and character developments",
      "- Notable details, memorable quotes, and revelations",
      "- Outcome and anything else important for future continuity",
      "Capture nuance without repeating verbatim. Make it comprehensive yet digestible.",
      "",
      "For the keywords field, provide 15-30 specific, descriptive, relevant keywords for keyword retrieval via word-matching in chat context. Keywords must be concrete and scene-specific (locations, objects, proper nouns, unique actions). Do not use abstract themes (e.g., \"sadness\", \"love\") or character names.",
      "",
      "Return ONLY the JSON, no other text.",
    ].join("\n"),
  },
  {
    key: "summarize",
    displayName: "Summarize",
    prompt: [
      "Analyze the following roleplay scene and return a structured summary as JSON.",
      "",
      TARGET_DIRECTIVE,
      "",
      "You must respond with ONLY valid JSON in this exact format:",
      "{",
      "  \"title\": \"Short scene title (1-3 words)\",",
      "  \"opener\": \"{{memoria_opener}}\",",
      "  \"content\": \"Detailed summary with markdown headers...\",",
      "  \"keywords\": [\"keyword1\", \"keyword2\", \"keyword3\"],",
      "  \"short_comment\": \"{{memoria_short_comment_rules}}\"",
      "}",
      "",
      "The opener field MUST be the exact string shown above, copied verbatim. Do not rephrase it or invent your own.",
      "",
      "For the content field, create a detailed bullet-point summary using markdown with these headers (skip and ignore all OOC conversation/interaction):",
      "- **Timeline**: Day/time this scene covers.",
      "- **Story Beats**: List all important plot events and story developments that occurred.",
      "- **Key Interactions**: Describe the important character interactions, dialogue highlights, and relationship developments.",
      "- **Notable Details**: Mention any important objects, settings, revelations, or details that might be relevant for future interactions.",
      "- **Outcome**: Summarize the result, resolution, or state of affairs at the end of the scene.",
      "",
      "For the keywords field, provide 15-30 specific, descriptive, relevant keywords that would help a keyworded database find this conversation again if something is mentioned. Keywords must be concrete and scene-specific (locations, objects, proper nouns, unique actions). Do not use abstract themes (e.g., \"sadness\", \"love\") or character names.",
      "",
      "Capture all important information - comprehensiveness within the target budget matters more than terseness.",
      "",
      "Return ONLY the JSON, no other text.",
    ].join("\n"),
  },
  {
    key: "synopsis",
    displayName: "Synopsis",
    prompt: [
      "Analyze the following roleplay scene in the context of previous summaries (if available) and return a comprehensive synopsis as JSON.",
      "",
      TARGET_DIRECTIVE,
      "",
      "You must respond with ONLY valid JSON in this exact format:",
      "{",
      "  \"title\": \"Short, descriptive scene title (3-6 words)\",",
      "  \"opener\": \"{{memoria_opener}}\",",
      "  \"content\": \"Long detailed synopsis with markdown structure...\",",
      "  \"keywords\": [\"keyword1\", \"keyword2\", \"keyword3\"],",
      "  \"short_comment\": \"{{memoria_short_comment_rules}}\"",
      "}",
      "",
      "The opener field MUST be the exact string shown above, copied verbatim. Do not rephrase it or invent your own.",
      "",
      "For the content field, create a beat-by-beat summary of the scene that *replaces reading the full scene* while preserving all plot-relevant nuance, reading like a clean, structured scene log - concise yet complete. Exercise judgment as to whether an interaction is flavor-only or truly affects the plot. Flavor scenes may be captured through key exchanges and skipped when recording story beats.",
      "",
      "Write in **past tense**, **third-person**, and exclude all [OOC] or meta discussion.",
      "Use concrete nouns (e.g., \"rice cooker\" > \"appliance\").",
      "Only use adjectives/adverbs when they materially affect tone, emotion, or characterization.",
      "Focus on **cause → intention → reaction → consequence** chains for clarity and compression.",
      "",
      "# [Scene Title]",
      "**Timeline**: (day/time)",
      "",
      "## Story Beats",
      "- Present all major actions, revelations, and emotional shifts in order.",
      "- Capture clear cause-effect logic: what triggered what, and why it mattered.",
      "- Only include plot-affecting interactions; do not capture flavor-only beats.",
      "",
      "## Character Dynamics",
      "- Summarize how each character's **motives, emotions, and relationships** evolved.",
      "- Include subtext, tension, or silent implications.",
      "- Highlight key beats of conflict, vulnerability, trust, or power shifts.",
      "",
      "## Key Exchanges",
      "- Include only pivotal dialogue that defines tone, emotion, or change.",
      "- Attribute speakers by name; keep quotes short but exact.",
      "- BE SELECTIVE. Maximum of 8 quotes.",
      "",
      "## Outcome & Continuity",
      "- Detail resulting **decisions, emotional states, physical effects, or narrative consequences**.",
      "- Include all elements that influence future continuity (knowledge, relationships, injuries, promises, etc.).",
      "- Note any unresolved threads or foreshadowed elements.",
      "",
      "Write compactly but completely - every line should add new information or insight.",
      "Synthesize redundant actions or dialogue into unified cause-effect-emotion beats.",
      "Favor compression over coverage whenever the two conflict; omit anything that can be inferred from context or established characterization.",
      "",
      "For the keywords field:",
      "",
      "Generate **15-30 standalone topical keywords** that function as retrieval tags, not micro-summaries.",
      "Keywords must be:",
      "- **Concrete and scene-specific** (locations, objects, proper nouns, unique actions, repeated motifs).",
      "- **One concept per keyword** - do NOT combine multiple ideas into one keyword.",
      "- **Useful for retrieval if the user later mentions that noun or action alone**, not only in a specific context.",
      "- Not character names.",
      "- **Not thematic, emotional, or abstract.** Stop-list: intimacy, vulnerability, trust, dominance, submission, power dynamics, boundaries, jealousy, aftercare, longing, consent, emotional connection.",
      "",
      "Avoid:",
      "- Overly specific compound keywords (\"David Tokyo marriage\").",
      "- Narrative or plot-summary style keywords (\"art dealer date fail\").",
      "- Keywords that contain multiple facts or descriptors.",
      "- Keywords that only make sense when the whole scene is remembered.",
      "",
      "Prefer:",
      "- Proper nouns (e.g., \"Chinatown\", \"Ritz-Carlton bar\").",
      "- Specific physical objects (\"CPAP machine\", \"chocolate chip cookies\").",
      "- Distinctive actions (\"cookie baking\", \"piano apology\").",
      "- Unique phrases or identifiers from the scene (\"pack for forever\", \"dick-measuring contest\").",
      "",
      "Return ONLY the JSON, no other text.",
    ].join("\n"),
  },
  {
    key: "minimal",
    displayName: "Minimal",
    prompt: [
      "Analyze the following roleplay scene and return an ultra-concise memory as JSON. Prioritize compression over coverage. Capture only load-bearing plot moves and the single most important consequence; omit anything inferable from context.",
      "",
      TARGET_DIRECTIVE,
      "",
      "You must respond with ONLY valid JSON in this exact format:",
      "{",
      "  \"title\": \"Short scene title (1-3 words)\",",
      "  \"opener\": \"{{memoria_opener}}\",",
      "  \"content\": \"Ultra-concise prose summary, prioritizing compression over coverage...\",",
      "  \"keywords\": [\"keyword1\", \"keyword2\", \"keyword3\"],",
      "  \"short_comment\": \"{{memoria_short_comment_rules}}\"",
      "}",
      "",
      "The opener field MUST be the exact string shown above, copied verbatim. Do not rephrase it or invent your own.",
      "",
      "For the content field: prose only, past tense, third person. Skip all [OOC]/meta. Skip flavor and atmosphere. Keep only events that change state, decisions that bind future scenes, or revelations the characters cannot un-know.",
      "",
      "For the keywords field, generate 15-30 specific, descriptive, highly relevant keywords for database retrieval - focus on the most important terms that would help find this scene later. Keywords must be concrete and scene-specific (locations, objects, proper nouns, unique actions). Do not use abstract themes (e.g., \"sadness\", \"love\") or character names.",
      "",
      "Return ONLY the JSON, no other text.",
    ].join("\n"),
  },
];

export const BUILTIN_ARC_PRESETS: BuiltInPreset[] = [
  {
    key: "arc_default",
    displayName: "Arc",
    prompt: [
      "You are an expert narrative analyst and memory-engine assistant.",
      "Your task is to take multiple scene summaries (of varying detail and formatting), normalize them, reconstruct the full chronology, identify a self-contained story arc, and output a single memory arc entry in JSON.",
      "",
      "The arc must be token-efficient, plot-accurate, and compatible with long-running RP memory systems.",
      "",
      TARGET_DIRECTIVE,
      "",
      "Strict output format (JSON only; no markdown, no prose outside JSON):",
      "{",
      "  \"title\": \"Short descriptive arc title (3-6 words)\",",
      "  \"opener\": \"{{memoria_opener}}\",",
      "  \"content\": \"Structured arc summary as a single string (see Summary Content Structure below).\",",
      "  \"keywords\": [\"keyword1\", \"keyword2\"],",
      "  \"short_comment\": \"{{memoria_short_comment_rules}}\"",
      "}",
      "",
      "The opener field MUST be the exact string shown above, copied verbatim. Do not rephrase it or invent your own.",
      "",
      "Notes:",
      "- Respect chronology of the source chapters (oldest first).",
      "- If some source chapters do not fit the arc you produce, summarize the arc anyway and ignore the outliers.",
      "",
      "PROCESS",
      "",
      "STEP 1 - UNIFIED STORY (internal only)",
      "- Combine ALL provided chapter summaries into a single chronological retelling.",
      "- Ignore OOC/meta content.",
      "- Preserve plot-relevant events, character choices, emotional shifts, decisions, consequences, conflicts, promises, boundary negotiations.",
      "- Exclude flavor-only content unless it affects future behavior.",
      "- Normalize to past-tense, third-person.",
      "- Focus on cause → intention → reaction → consequence chains.",
      "- Do NOT output this unified story.",
      "",
      "STEP 2 - IDENTIFY THE STORY ARC",
      "- From the unified story, identify the single self-contained arc that represents the most significant narrative movement across these chapters.",
      "",
      "STEP 3 - BUILD THE ARC OBJECT",
      "",
      "title:",
      "- 3-6 words, descriptive of the arc's core.",
      "",
      "content (the entire \"Summary Content Structure\" below must appear inside this single string; use headings and bullets as plain text):",
      "",
      "Summary Content Structure (follow inside the content string):",
      "",
      "# [Arc Title]",
      "Time period: What timeframe the arc covers (e.g. \"March 3-10\", \"Week of July 15\").",
      "",
      "Arc Premise: One sentence describing what this arc is about.",
      "",
      "## Major Beats",
      "- 3-7 bullets capturing the major plot movements of this arc",
      "- Focus on cause → effect logic",
      "- Include only plot-affecting events",
      "",
      "## Character Dynamics",
      "- 1-2 paragraphs describing how the characters' emotions, motives, boundaries, or relationships changed",
      "- Include subtext, tension shifts, power exchange changes, new trust/vulnerabilities, or new conflicts",
      "- Include silent implications if relevant",
      "",
      "## Key Exchanges",
      "- Up to 8 short, exact quotes",
      "- Only include dialogue that materially shifted tone, emotion, or relationship dynamics",
      "",
      "## Outcome & Continuity",
      "- 4-8 bullets capturing:",
      "  - decisions",
      "  - promises",
      "  - new emotional states",
      "  - new routines/rituals",
      "  - injuries or physical changes",
      "  - foreshadowed future events",
      "  - unresolved threads",
      "  - permanent consequences",
      "",
      "STEP 4 - KEYWORDS",
      "- Provide 15-30 standalone retrieval keywords.",
      "",
      "MUST:",
      "- Concrete nouns, physical objects, places, proper nouns, distinctive actions, or memorable scene elements",
      "- Each keyword = ONE concept only",
      "- Each keyword must be retrievable if mentioned ALONE",
      "- Use ONLY nouns or noun-phrases",
      "",
      "MUST NOT:",
      "- No narrative/summary keywords (\"start of affair\", \"argument resolved\")",
      "- No emotional/abstract words (intimacy, vulnerability, trust, jealousy, dominance, submission, aftercare, connection, longing, etc.)",
      "- No multi-fact keywords (\"Denver airport Lyft ride and call\")",
      "- No themes or vibes",
      "",
      "Examples of valid keywords:",
      "- Four Seasons bar",
      "- Macallan 25",
      "- private elevator",
      "- Aston Martin",
      "- CPAP machine",
      "- Gramercy Tavern",
      "- yuzu soda",
      "- satellite map",
      "- Life360 app",
      "- marble desk",
      "- \"pack for forever\"",
      "- \"dick-measuring contest\"",
      "",
      "JSON-only:",
      "- Return only the JSON object described above.",
      "- No markdown fences, no commentary, no system prompts, no extra text.",
    ].join("\n"),
  },
];

export const BUILTIN_VOLUME_PRESETS: BuiltInPreset[] = [
  {
    key: "volume_default",
    displayName: "Volume",
    prompt: [
      "You are an expert narrative analyst and memory-engine assistant.",
      "Your task is to take multiple story ARC summaries (each already a condensed span of the story), normalize them, reconstruct the full chronology, and output a single consolidated VOLUME entry in JSON.",
      "",
      "A volume is the highest compression tier: it replaces all of its source arcs in a long-running RP memory system, so it must preserve everything future scenes may depend on while being far more compact than the arcs combined.",
      "",
      TARGET_DIRECTIVE,
      "",
      "Strict output format (JSON only; no markdown, no prose outside JSON):",
      "{",
      "  \"title\": \"Short descriptive volume title (3-6 words)\",",
      "  \"opener\": \"{{memoria_opener}}\",",
      "  \"content\": \"Structured volume summary as a single string (see Summary Content Structure below).\",",
      "  \"keywords\": [\"keyword1\", \"keyword2\"],",
      "  \"short_comment\": \"{{memoria_short_comment_rules}}\"",
      "}",
      "",
      "The opener field MUST be the exact string shown above, copied verbatim. Do not rephrase it or invent your own.",
      "",
      "Notes:",
      "- Respect chronology of the source arcs (oldest first).",
      "- Merge overlapping or repeated information across arcs into single beats.",
      "- Prefer whole-story trajectory over scene detail: what changed permanently matters more than how each scene played out.",
      "",
      "Summary Content Structure (follow inside the content string; use headings and bullets as plain text):",
      "",
      "# [Volume Title]",
      "Time period: What timeframe the volume covers.",
      "",
      "Volume Premise: One or two sentences describing the overall movement of the story across these arcs.",
      "",
      "## Major Beats",
      "- 5-10 bullets capturing the major plot movements across all arcs",
      "- Focus on cause → effect logic and permanent consequences",
      "- Include only plot-affecting events",
      "",
      "## Character Dynamics",
      "- 1-3 paragraphs describing how the characters' motives, emotions, boundaries, and relationships evolved across the volume",
      "- Capture the net change from the start of the first arc to the end of the last",
      "",
      "## Key Exchanges",
      "- Up to 8 short, exact quotes that defined the volume",
      "- Only dialogue that materially shifted tone, emotion, or relationship dynamics",
      "",
      "## Outcome & Continuity",
      "- 5-10 bullets capturing decisions, promises, emotional states, routines, injuries or physical changes, foreshadowed events, unresolved threads, and permanent consequences",
      "",
      "KEYWORDS",
      "- Provide 15-30 standalone retrieval keywords.",
      "- Concrete nouns, physical objects, places, proper nouns, distinctive actions, or memorable elements only.",
      "- Each keyword = ONE concept, retrievable if mentioned alone.",
      "- No narrative keywords, no emotional or abstract words, no multi-fact keywords, no character names.",
      "",
      "JSON-only:",
      "- Return only the JSON object described above.",
      "- No markdown fences, no commentary, no extra text.",
    ].join("\n"),
  },
];

export function findBuiltInPreset(category: "chapter" | "arc" | "volume", key: string): BuiltInPreset | null {
  const pool = category === "arc" ? BUILTIN_ARC_PRESETS : category === "volume" ? BUILTIN_VOLUME_PRESETS : BUILTIN_CHAPTER_PRESETS;
  return pool.find((p) => p.key === key) ?? null;
}

export interface ImportedPresetMap {
  chapter: { key: string; displayName: string; prompt: string }[];
  arc: { key: string; displayName: string; prompt: string }[];
}

export function parseStmbPresetExport(raw: unknown, category: "chapter" | "arc"): ImportedPresetMap[keyof ImportedPresetMap] {
  const out: { key: string; displayName: string; prompt: string }[] = [];
  if (!raw || typeof raw !== "object" || Array.isArray(raw)) return out;
  const overrides = (raw as { overrides?: unknown }).overrides;
  if (!overrides || typeof overrides !== "object" || Array.isArray(overrides)) return out;
  for (const [k, v] of Object.entries(overrides as Record<string, unknown>)) {
    if (!v || typeof v !== "object") continue;
    const node = v as { displayName?: unknown; prompt?: unknown };
    if (typeof node.prompt !== "string" || !node.prompt.trim()) continue;
    const key = sanitizeKey(`${category}_${k}`);
    const displayName = typeof node.displayName === "string" && node.displayName.trim()
      ? node.displayName
      : k;
    out.push({ key, displayName, prompt: node.prompt });
  }
  return out;
}

function sanitizeKey(raw: string): string {
  const cleaned = raw
    .toLowerCase()
    .replace(/[^a-z0-9_]+/g, "_")
    .replace(/^_+|_+$/g, "")
    .slice(0, 80);
  if (cleaned) return cleaned;
  return `preset_${Date.now().toString(36)}_${Math.random().toString(36).slice(2, 8)}`;
}
